name: Deploy SiparisApi to Azure App Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_VERSION: "9.0.x"
  PROJECT_PATH: "SiparisApi/SiparisApi.csproj"
  SOLUTION_PATH: "SiparisApi.sln"
  PUBLISH_DIR: "SiparisApi/publish"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build (Release)
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Publish
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} \
            --configuration Release \
            --no-build \
            --self-contained false \
            --output ${{ env.PUBLISH_DIR }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "bilalgurseliparis"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ${{ env.PUBLISH_DIR }}/.

      - name: Warm-up ping (optional)
        run: |
          curl -sS -m 10 https://bilalgurseliparis.azurewebsites.net/ || true
